version: '3'
services:
  vue-app:
    image: vue-app
    build: ./clientunsplash/
    stdin_open: true
    ports:
      - '8080:8080'
    networks:
      - mevn-app
  api-server:
    image: api-server
    build: ./
    ports:
      - '5000:5000'
    networks:
      - mevn-app
networks:
  mevn-app:
    driver: bridge